# Generated by Django 5.0.1 on 2024-02-01 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("squares", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="square",
            name="date_created",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="square",
            name="date_uploaded",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="square",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="square",
            name="notes",
            field=models.TextField(default="", blank=True),
            preserve_default=False,
        ),
    ]
