# Generated by Django 5.0.1 on 2024-02-13 16:16

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("squares", "0003_alter_square_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="square",
            name="date_uploaded",
        ),
        migrations.AddField(
            model_name="square",
            name="date_time_uploaded",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
