# Generated by Django 5.0.1 on 2024-02-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("squares", "0004_remove_square_date_uploaded_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="square",
            name="date_time_uploaded",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
