# Generated by Django 5.0.1 on 2024-04-29 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("squares", "0005_alter_square_creator"),
        ("squares", "0005_alter_square_date_time_uploaded"),
    ]

    operations = []
