# Generated by Django 5.0.6 on 2024-05-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squares", "0006_merge_20240429_1337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="square",
            name="creator",
            field=models.CharField(
                help_text='Your name, or a pseudonym. This will be displayed publicly - if you\'d rather not include any name at all, write "Anon".',
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="square",
            name="date_created",
            field=models.DateField(
                help_text="Enter the date when you finished the square, not including adding it to the blanket."
            ),
        ),
        migrations.AlterField(
            model_name="square",
            name="description",
            field=models.TextField(
                help_text='A concise visual description of your square. For example, "red and yellow striped square".',
                verbose_name="alt_text",
            ),
        ),
        migrations.AlterField(
            model_name="square",
            name="name",
            field=models.CharField(help_text="A name for the square.", max_length=256),
        ),
        migrations.AlterField(
            model_name="square",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Anything you'd like others to know about the square - for example, why you chose the design, or what the colours mean.",
            ),
        ),
    ]
