# Generated by Django 5.0.6 on 2024-05-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squares", "0007_alter_square_creator_alter_square_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="square",
            name="description",
            field=models.CharField(
                help_text='A concise visual description of your square. For example, "red and yellow striped square".',
                max_length=1000,
                verbose_name="alt_text",
            ),
        ),
    ]
