# Generated by Django 5.0.6 on 2026-06-07 10:27

from django.db import migrations, models
import os
import io
from PIL import Image


def create_thumbnails(apps, schema_editor):
    Square = apps.get_model("squares", "Square")
    for square in Square.objects.all():
        path = square.image.path
        output_size = (100, 100)
        imag = Image.open(path)
        imag.thumbnail(output_size)
        imag.save(path + ".thumbnail")


class Migration(migrations.Migration):

    dependencies = [
        ("squares", "0010_alter_square_date_created_alter_square_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="square",
            name="thumbnail",
            field=models.ImageField(
                help_text="A thumbnail of the square, generated automatically from the uploaded image.",
                null=True,
                upload_to="thumbnails/squares/",
            ),
        ),
        # migrations.RunPython(create_thumbnails, migrations.RunPython.noop),
    ]
