services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    secrets:
      - postgres_user
      - postgres_password
    environment:
      - POSTGRES_DB=community_blanket_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
  web:
    build: ./blanket_site/
    command: uwsgi --socket :8000 --module blanket_site.wsgi
    volumes:
      - ./blanket_site:/code
      - /var/www/blanket_site/static:/code/staticfiles
      - /var/www/blanket_site/media:/code/mediafiles
    ports:
      - "8000:8000"
    secrets:
      - django_variables
    environment:
      RUNNING_IN_CONTAINER: True

secrets:
   django_variables:
     file: secret_variables_django.env
   postgres_password:
     file: secret_postgres_password.txt
   postgres_user:
     file: secret_postgres_user.txt

volumes:
  postgres_data: