services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=community_blanket_db
      - POSTGRES_USER=Jaybird4139
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./blanket_site/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./blanket_site:/code
    ports:
      - "8000:8000"
    secrets:
      - django_variables
    environment:
      RUNNING_IN_CONTAINER: True

secrets:
   django_variables:
     file: variables.env

volumes:
  postgres_data: