# Generated by Django 5.0.1 on 2024-04-28 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('squares', '0005_alter_square_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blanket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('creator', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BlanketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
                ('blanket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blankets.blanket')),
                ('square', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='squares.square')),
            ],
        ),
    ]
