# Generated by Django 5.0.1 on 2024-04-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blankets", "0001_initial"),
        ("squares", "0005_alter_square_creator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blanket",
            old_name="height",
            new_name="num_cols",
        ),
        migrations.RenameField(
            model_name="blanket",
            old_name="width",
            new_name="num_rows",
        ),
        migrations.RemoveField(
            model_name="blanketitem",
            name="location_x",
        ),
        migrations.RemoveField(
            model_name="blanketitem",
            name="location_y",
        ),
        migrations.AddField(
            model_name="blanketitem",
            name="column",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blanketitem",
            name="row",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
