# Generated by Django 5.0.6 on 2024-05-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blankets", "0002_rename_height_blanket_num_cols_and_more"),
        ("squares", "0006_merge_20240429_1337"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="blanketitem",
            constraint=models.UniqueConstraint(
                models.F("square"), name="unique_square"
            ),
        ),
        migrations.AddConstraint(
            model_name="blanketitem",
            constraint=models.UniqueConstraint(
                models.F("blanket"),
                models.F("column"),
                models.F("row"),
                name="unique_blanket_column_row",
            ),
        ),
    ]
