# Generated by Django 5.0.6 on 2026-07-07 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("planets", "0004_remove_planet_mass_not_negative_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("creator", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("num_cols", models.IntegerField()),
                ("num_rows", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SolarSystemItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column", models.PositiveIntegerField()),
                ("row", models.PositiveIntegerField()),
                (
                    "planet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="planets.planet"
                    ),
                ),
                (
                    "solar_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solar_systems.solarsystem",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="solarsystemitem",
            constraint=models.UniqueConstraint(
                models.F("planet"), name="unique_planet"
            ),
        ),
        migrations.AddConstraint(
            model_name="solarsystemitem",
            constraint=models.UniqueConstraint(
                models.F("solar_system"),
                models.F("column"),
                models.F("row"),
                name="unique_solar_system_column_row",
            ),
        ),
    ]
