# Generated by Django 5.0.6 on 2026-07-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planets", "0004_remove_planet_mass_not_negative_and_more"),
        ("solar_systems", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="solarsystemitem", name="unique_solar_system_column_row",
        ),
        migrations.RemoveField(model_name="solarsystem", name="num_cols",),
        migrations.RemoveField(model_name="solarsystem", name="num_rows",),
        migrations.RemoveField(model_name="solarsystemitem", name="column",),
        migrations.RemoveField(model_name="solarsystemitem", name="row",),
        migrations.AddField(
            model_name="solarsystem",
            name="max_distance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="solarsystemitem",
            name="angle",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="solarsystemitem",
            name="distance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="solarsystemitem",
            constraint=models.UniqueConstraint(
                models.F("solar_system"),
                models.F("distance"),
                models.F("angle"),
                name="unique_solar_system_coords",
            ),
        ),
        migrations.AddConstraint(
            model_name="solarsystemitem",
            constraint=models.CheckConstraint(
                check=models.Q(("distance__gte", 0)),
                name="distance_not_negative",
                violation_error_message="Distance cannot be negative.",
            ),
        ),
        migrations.AddConstraint(
            model_name="solarsystemitem",
            constraint=models.CheckConstraint(
                check=models.Q(("angle__lt", 360)),
                name="angle_within_circle",
                violation_error_message="Angle cannot be more than 360 degrees.",
            ),
        ),
    ]
