# Generated by Django 5.0.6 on 2026-07-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_systems", "0002_update_coordinate_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solarsystem",
            name="max_distance",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The maximum size of the solar system in <b>centimetres</b>.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="solarsystemitem",
            name="angle",
            field=models.PositiveIntegerField(
                help_text="The number of <b>degrees</b> the planet has proceeded anticlockwise round its orbit."
            ),
        ),
        migrations.AlterField(
            model_name="solarsystemitem",
            name="distance",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The distance in <b>centimetres</b> between the planet and the centre of the solar system.",
                max_digits=10,
            ),
        ),
    ]
