# Generated by Django 5.2.16 on 2026-07-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solar_systems", "0003_alter_solarsystem_max_distance_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="solarsystemitem", name="unique_solar_system_coords",
        ),
    ]
