# Generated by Django 5.0.6 on 2026-07-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A name for the planet.", max_length=256
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="A picture of the planet. Ensure the image is square (aspect ratio 1:1), and that the edges of the image are cropped as close as possible to the edge of the planet, without cutting off part of the planet.",
                        upload_to="uploads/planets/%Y/%m/%d/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        help_text="A thumbnail of the planet, generated automatically from the uploaded image.",
                        null=True,
                        upload_to="thumbnails/planets/",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        help_text='Your name, or a pseudonym. This will be displayed publicly - if you\'d rather not include any name at all, write "Anon".',
                        max_length=256,
                    ),
                ),
                (
                    "date_created",
                    models.DateField(
                        help_text="Enter the date when you finished the planet, not including adding it to the blanket. Format: YYYY-MM-DD"
                    ),
                ),
                ("date_time_uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.CharField(
                        help_text='A concise visual description of your planet. For example, "red and yellow striped planet".',
                        max_length=1000,
                        verbose_name="Alt text",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Anything you'd like others to know about the planet - for example, why you chose the design, or what the colours mean.",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
