# Generated by Django 5.0.6 on 2026-07-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planet",
            name="diameter",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="The diameter of your planet in **centimetres**. There are measuring tools in the Arts tent. If you don't have measuring tools to hand, make a guess or enter 0.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="fun_fact",
            field=models.TextField(
                blank=True,
                help_text='A fun fact about your planet. For example, "the red spot is a giant storm", "the inhabitants are hackers", or "it\'s named after the discoverer\'s favourite Linux distro"',
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="mass",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="The mass of your planet in **grams**. There are weighing scales in the Arts tent. If you don't have weighing scales to hand, make a guess or enter 0.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="creator",
            field=models.CharField(
                help_text='Your name, or a pseudonym. This will be displayed publicly - if you\'d rather not include any name at all, write "Anon".',
                max_length=256,
                verbose_name="Discoverer",
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="date_created",
            field=models.DateField(
                help_text="Enter the date when you discovered (finished) the planet, not including adding it to the solar system. Format: YYYY-MM-DD",
                verbose_name="Date discovered",
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Anything you'd like others to know about the planet - for example, how you made it, or if the colours mean something to you.",
            ),
        ),
        migrations.AddConstraint(
            model_name="planet",
            constraint=models.CheckConstraint(
                check=models.Q(("mass__gte", 0)), name="mass_not_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="planet",
            constraint=models.CheckConstraint(
                check=models.Q(("diameter__gte", 0)), name="diameter_not_negative"
            ),
        ),
    ]
