# Generated by Django 5.0.6 on 2026-07-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planets", "0002_planet_diameter_planet_fun_fact_planet_mass_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planet",
            name="description",
            field=models.CharField(
                help_text='A concise visual description of the planet. For example, "red and yellow striped planet". This helps blind & low vision astronomers know what the planet looks like.',
                max_length=1000,
                verbose_name="Visual description",
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="diameter",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="The diameter of your planet in <b>centimetres</b>. There are measuring tools in the Arts tent. If you don't have measuring tools to hand, make a guess or enter 0.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="fun_fact",
            field=models.TextField(
                blank=True,
                help_text='A fun fact about your planet. For example, "the red spot is a giant storm", "the inhabitants are hackers", or "it\'s named after the discoverer\'s favourite Linux distro".',
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="mass",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="The mass of your planet in <b>grams</b>. There are weighing scales in the Arts tent. If you don't have weighing scales to hand, make a guess or enter 0.",
                max_digits=10,
            ),
        ),
    ]
