# Generated by Django 5.0.6 on 2026-07-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planets", "0003_alter_planet_description_alter_planet_diameter_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="planet", name="mass_not_negative",),
        migrations.RemoveConstraint(model_name="planet", name="diameter_not_negative",),
        migrations.AddConstraint(
            model_name="planet",
            constraint=models.CheckConstraint(
                check=models.Q(("mass__gte", 0)),
                name="mass_not_negative",
                violation_error_message="Mass cannot be negative.",
            ),
        ),
        migrations.AddConstraint(
            model_name="planet",
            constraint=models.CheckConstraint(
                check=models.Q(("diameter__gte", 0)),
                name="diameter_not_negative",
                violation_error_message="Diameter cannot be negative.",
            ),
        ),
    ]
