# Generated by Django 5.2.16 on 2026-07-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planets", "0004_remove_planet_mass_not_negative_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planet",
            name="diameter",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='The diameter of your planet in <b>centimetres</b>. There are measuring tools in <a href="https://map.emfcamp.org/#18.5/52.04028161496325/-2.378171671045834/m=52.04028161496325,-2.378171671045834">Tekhnē-cal Village</a>. If you don\'t have measuring tools to hand, make a guess or enter 0.',
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="mass",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='The mass of your planet in <b>grams</b>. There are weighing scales in <a href="https://map.emfcamp.org/#18.5/52.04028161496325/-2.378171671045834/m=52.04028161496325,-2.378171671045834">Tekhnē-cal Village</a>. If you don\'t have weighing scales to hand, make a guess or enter 0.',
                max_digits=10,
            ),
        ),
    ]
